# Generated by Django 6.0 on 2025-12-26 22:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True, verbose_name='Símbolo')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'db_table': 'portfolios_asset',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('initial_value', models.DecimalField(decimal_places=2, help_text='Valor inicial del portafolio en dólares', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor inicial (V_0)')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolios',
                'db_table': 'portfolios_portfolio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha')),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Cantidad de unidades del activo', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cantidad (c_i,t)')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.asset', verbose_name='Activo')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='main.portfolio', verbose_name='Portafolio')),
            ],
            options={
                'verbose_name': 'Tenencia',
                'verbose_name_plural': 'Tenencias',
                'db_table': 'portfolios_holding',
                'ordering': ['date', 'portfolio', 'asset'],
                'indexes': [models.Index(fields=['portfolio', 'date'], name='portfolios__portfol_d9f503_idx'), models.Index(fields=['date'], name='portfolios__date_10b99a_idx')],
                'unique_together': {('portfolio', 'asset', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=8, help_text='Porcentaje del activo en el portafolio (0.0 a 1.0)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Weight (w_i,0)')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.asset', verbose_name='Activo')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='main.portfolio', verbose_name='Portafolio')),
            ],
            options={
                'verbose_name': 'Peso del Portafolio',
                'verbose_name_plural': 'Pesos de Portafolios',
                'db_table': 'portfolios_weight',
                'unique_together': {('portfolio', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha')),
                ('price', models.DecimalField(decimal_places=6, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Precio (p_i,t)')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.asset', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
                'db_table': 'portfolios_price',
                'ordering': ['date', 'asset'],
                'indexes': [models.Index(fields=['asset', 'date'], name='portfolios__asset_i_2b7aca_idx'), models.Index(fields=['date'], name='portfolios__date_324b1a_idx')],
                'unique_together': {('asset', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta')], max_length=4, verbose_name='Tipo de transacción')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto en dólares de la transacción', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.asset', verbose_name='Activo')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.portfolio', verbose_name='Portafolio')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'portfolios_transaction',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['portfolio', 'date'], name='portfolios__portfol_212a11_idx'), models.Index(fields=['date'], name='portfolios__date_ccb786_idx')],
            },
        ),
    ]
