# Generated by Django 6.0 on 2025-12-27 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioweight',
            options={'verbose_name': 'Porcentaje del Portafolio', 'verbose_name_plural': 'Porcentajes de Portafolios'},
        ),
    ]
